# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: iot_data.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'iot_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eiot_data.proto\x12\x03iot\"w\n\x10TelemetryRequest\x12\x11\n\tdevice_id\x18\x01 \x01(\t\x12\x13\n\x0btemperature\x18\x02 \x01(\x01\x12\x10\n\x08humidity\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\t\x12\x16\n\x0estatus_payload\x18\x05 \x01(\x0c\"5\n\x11TelemetryResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2L\n\nIotService\x12>\n\rSendTelemetry\x12\x15.iot.TelemetryRequest\x1a\x16.iot.TelemetryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'iot_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TELEMETRYREQUEST']._serialized_start=23
  _globals['_TELEMETRYREQUEST']._serialized_end=142
  _globals['_TELEMETRYRESPONSE']._serialized_start=144
  _globals['_TELEMETRYRESPONSE']._serialized_end=197
  _globals['_IOTSERVICE']._serialized_start=199
  _globals['_IOTSERVICE']._serialized_end=275
# @@protoc_insertion_point(module_scope)
